### ISSUE TITLE
Ionscale support?

### ISSUE THREAD

**Issue by unixfox** [gurucomputing/headscale-ui#128]
Ionscale is a new project like headscale that reimplement the control plane of tailscale.

This project seems more active, have more features compared to headscale and the author seems reactive when it comes to bug fixes.

I think ionscale has an API (not documented): https://github.com/jsiebens/ionscale/blob/main/pkg/client/ionscale/client.go that listen on the same port as the control plane. And this API uses protobuf for the data transfer: https://github.com/jsiebens/ionscale/tree/main/proto/ionscale/v1

I would really like to see maybe an adapted version of headscale-ui with the support of ionscale. Is it possible? What would be the effort of supporting this other software? @adrum Would you be interested in some kind of support for ionscale in headscale-ui?

**Comment by routerino** [comment]
Feasibly this could be done, but doing so would essentially require re-writing the entire api component of the codebase. And likely requires tighter integration in lieu of an authentication component.

Given that this project is in maintenance mode essentially, it's unlikely unless ionscale takes off and headscale winds down.

**Comment by jlbribeiro** [comment]
Hey @unixfox, not focusing on the merits of one project vs. the other,
> [Ionscale] seems more active

just wanted to note that Headscale has had [3 alpha releases](https://github.com/juanfont/headscale/releases) since the latest stable (0.22.3), the [last one released 2 weeks ago](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha3). Just wanted to mention that because I hadn't noticed them until very recently.

**Comment by routerino** [comment]
Hi all,

Given that I've found updating just to keep up with headscale is competing with life/work priorities, I can safely say that this feature is unlikely to progress. I'll keep an eye on the ionscale project though for sure.
